### ISSUE TITLE
Supremus: Kite/Tank timers broken

### ISSUE THREAD

**Issue by Siarkowy** [SiarkowyForks/DBM-5man#1]
**Actual behavior**
Kite/Tank phase timers are firing randomly to boss emotes.

**Expected behavior**
Kite and Tank phases should interchange every single minute.

**Comment by BlessedPinkie** [comment]
It could be that the emotes are going off at the wrong times in the script, if that's what dbm relies on to track the timers.

**Comment by Siarkowy** [comment]
Yeah, the emotes are incorrect server-side. I slightly rewrote phase tracking code to rely on fixed 1 minute timer to switch phase instead of relying on emotes, only needs some live testing.
